### ISSUE TITLE
Why the  imageattachments  Extensions didn't update

### ISSUE THREAD

**Issue by skywalker512** [sthinteresting/imageattachments#2]
The imageattachments only support beta.2.
Why didn't update

**Comment by kloknibor** [comment]
I also would love to see this plugin working! It looks great but currently it crashes flarum extension managent. Any chance this would get updated?

**Comment by oott123** [comment]
Sorry but now I don't have enough time to do so.
Actually, I almost give up it because Flarum update itself so slow.
Maybe I will start it again when Flarum goes to its first release.
Sorry again.

**Comment by kloknibor** [comment]
Well that is an pity to hear! Will see if someone else is willing to do so

Verstuurd vanaf mijn iPhone
