### ISSUE TITLE
is there any plan to support beta5 and above?

### ISSUE THREAD

**Issue by hick** [sthinteresting/imageattachments#5]
I checked the closed issues,  no plan ?

What's the main tech problem for this WARNING ?

```
WARNGING: There isn't any limit to uploading images. Please use at your own risk.
```

thx :)

**Comment by oott123** [comment]
Sorry, no plan for any new beta versions now. Maybe I will upgrade it when Flarum comes to production.

The warning means that the plugin won't check the content of your image. Maybe it will contains bad codes or so, and may cause problems on servers with wrong configuration.

Furthermore, this plugin won't limit the size or amount of uploading images. This may cause huge fee for bandwith or storage.

However, when you are using services like imgur, some limits will apply by them.
